feedback/models.py
from extensions import db


class Feedback(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String, nullable=False)
    text = db.Column(db.Text, nullable=False)

products/models.py
from flask_admin import form

from extensions import db


class Discount(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=True, nullable=False)
    size = db.Column(db.Integer, nullable=False)
    products = db.relationship('Product', backref='discount', lazy=True)


class Product(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, unique=True, nullable=False)
    description = db.Column(db.String, nullable=False)
    image = db.Column(db.Unicode(128))
    price = db.Column(db.Integer, nullable=False, default=99)
    discount_id = db.Column(db.Integer, db.ForeignKey('discount.id'), nullable=True)

    @property
    def thumbnail(self):
        return form.thumbgen_filename(self.image) if self.image else None

feedback/forms.py
from flask_wtf import FlaskForm
from wtforms import EmailField, TextAreaField
from wtforms.validators import DataRequired


class FeedbackForm(FlaskForm):
    email = EmailField('email', validators=[DataRequired()])
    text = TextAreaField('text', validators=[DataRequired()])

app.py
from flask import Flask
from flask_admin.contrib import sqla
from sqlalchemy.event import listens_for

from core.admin import ImageView, del_image
from extensions import admin, db, migrate
from products.models import Discount, Product
from feedback.models import Feedback
from products.views import blueprint as product_pb
from feedback.views import blueprint as feedback_pb


def create_app(config_object="settings"):
    app = Flask(__name__.split(".")[0])
    app.config.from_object(config_object)

    register_extensions(app)
    register_blueprints(app)
    register_admin()
    register_signals()

    return app


def register_extensions(app):
    db.init_app(app)
    migrate.init_app(app, db)
    admin.init_app(app)
    return None


def register_blueprints(app):
    app.register_blueprint(product_pb)
    app.register_blueprint(feedback_pb)
    return None


def register_admin():
    admin.add_view(ImageView(Product, db.session))
    admin.add_view(sqla.ModelView(Discount, db.session))
    admin.add_view(sqla.ModelView(Feedback, db.session))


def register_signals():
    listens_for(del_image, Product, 'after_delete')

feedback/views.py
from flask import Blueprint, redirect, render_template

from extensions import db
from feedback.forms import FeedbackForm
from feedback.models import Feedback

blueprint = Blueprint('feedback_form', __name__, url_prefix='/feedback', static_folder='../static')


@blueprint.route('/', methods=['GET', 'POST'])
def form_page():
    form = FeedbackForm()
    if form.validate_on_submit():
        feedback = Feedback(
            email=form.email.data,
            text=form.text.data,
        )
        db.session.add(feedback)
        db.session.commit()
        return redirect('/feedback/success')
    return render_template('feedback.html', form=form)


@blueprint.route('/success')
def success():
    return render_template('feedback_success.html')

products/views.py
from flask import Blueprint, render_template
from flask import request

from extensions import db
from products.models import Product

blueprint = Blueprint('products', __name__, url_prefix='/', static_folder='../static')


@blueprint.route('/')
def main_page():
    title = 'Аптека'
    description = 'Надёжный поставщик качественных лекарственных средств'
    submenu = [
        {'title': 'Заказать из наличия'},
        {'title': 'Помощь специалиста'},
    ]
    menu = [
        {'title': 'Доставка и оплата'},
        {'title': 'О нас'},
        {'title': 'Контакты'},
        {'title': 'Каталог', 'submenu': submenu},
    ]

    discount = request.args.get('discount')

    if discount:
        products = db.session.execute(db.select(Product).filter(Product.discount_id != None)).scalars()
    else:
        products = db.session.execute(db.select(Product)).scalars()

    context = {
        'title': title,
        'description': description,
        'menu': menu,
        'products': products,
    }
    return render_template('main.html', **context)


@blueprint.route('/add')
def add_product():
    pass

templates/about.html
{% extends "base.html" %}

{% block content %}
  <h1>About page</h1>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://unpkg.com/feather-icons"></script>
  </head>
  <body>
    {% include "header/header.html" %}
    <main class="py-5">
      {% block content %}
      {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script>
      feather.replace()
    </script>
  </body>
</html>

templates/feedback.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col">
        <form method="POST" action="/feedback">
          {{ form.csrf_token }}
          <p>{{ form.email.label }}</p>
          <p> {{ form.email }} </p>
          <p> {{ form.text.label }}</p>
          <p>{{ form.text }}</p>
          <input type="submit" value="Оставить обратную связь">
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/feedback_success.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col">
        <h1>Спасибо за вашу обратную связь!</h1>
      </div>
    </div>
  </div>
{% endblock %}

templates/header/burger.html
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

templates/header/header.html
<header>
  {% include "header/navigation.html" %}
</header>

templates/header/icons.html
<div class="navbar-icons">
  <span class="navbar-icon me-3">
      <i data-feather="shopping-cart"></i>
  </span>
  <span class="navbar-icon">
      <i data-feather="user"></i>
  </span>
</div>

templates/header/logo.html
<a class="navbar-brand" href="#">{{ title }}</a>

templates/header/menu.html
<div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">
  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
    {% for menu_item in menu %}
      {% if menu_item.submenu %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{ menu_item.title }}
          </a>
          <ul class="dropdown-menu">
            {% for submenu_item in menu_item.submenu %}
              <li>
                <a class="dropdown-item" href="#">{{ submenu_item.title }}</a>
              </li>
            {% endfor %}
          </ul>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">{{ menu_item.title }}</a>
        </li>
      {% endif %}
    {% endfor %}
  </ul>
</div>

templates/header/navigation.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    {% include "header/logo.html" %}
    {% include "header/burger.html" %}
    {% include "header/menu.html" %}
    {% include "header/icons.html" %}
  </div>
</nav>

templates/main.html
<a size ='10' title="Telegram" href="https://telegram.me/beaver_knithen" target="_blank"><img src="images/telegram_icon.jpg” alt="Написать в Telegram" /></a>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

<header>
<b>
<font size="6">
  <header>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-xxl">
          <a class="navbar-brand" href="#">Beaver_knithen</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="#">Доставка и оплата</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#"> О нас </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Контакты</a>
              </li>
                  <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Каталог
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Выбрать модель</a></li>
                  <li><a class="dropdown-item" href="#">Заказать из наличия</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Помощь специалиста</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li> 
              <h5>
              <a  href="https://pngicon.ru/zelenaja-korzina.html"><img src="https://pngicon.ru/file/uploads/basket-128x128.png" 
                alt="корзина" width="40" height="40"> </a>
              </h5>
              <h6>
                <font size="6">
                <li class="nav-item">
                  <a class="nav-link"  href="#">ЛК</a>
                </font size>
                </li>
              </h6>
            </ul>
            
          </div>
        </div>
      </nav>
</header>
</font size>
</b>

<!--_______________________________________________________________________________________-->
<style>
h1 {
  padding-left: 1px;
}
 

</style>

<!--_______________________________________________________________________________________-->
<h1><i>{{beaver_main_1}}</i></h1>
<h2><i>{{beaver_main_2}}</i></h2>        
<!--_______________________________________________________________________________________-->


<!--_______________________________________________________________________________________-->

<!--_______________________________________________________________________________________-->


<div class="container">
  <div class="row">
    <div class="col-sm">
      <h1>
      <div class="col-3">
        <img class = "w-100" src = https://i.pinimg.com/736x/7c/af/0a/7caf0a2961d2a76d98879bf695a644d3.jpg alt = "fon">
      </div>
    </h1>
    </div>
    <!--_______________________________________________________________________________________-->
    <div class="col-sm">
    </div>
    <div class="col">
        <button type="button" class="btn btn-outline-success">Цвет</button>
        <button type="button" class="btn btn-outline-success">Шерсть</button>
        <button type="button" class="btn btn-outline-success">Пошив</button>
        <button type="button" class="btn btn-outline-success">Узоры</button>
        <button type="button" class="btn btn-outline-success">Пол</button>
        <button type="button" class="btn btn-outline-success">Размер</button>
        <button type="button" class="btn btn-outline-success">Страна</button>
        <button type="button" class="btn btn-outline-success">Забрать из наличия</button>

    
        <div class="row">
          <div class="col-5"><form class="d-flex" role="search", col-8>
            <input style="height:70px" class="form-control me-" type="search"  placeholder ="Найти модель" aria-label="Поиск">
            <button class="btn btn-outline-success" type="submit">Поиск</button>
          </form></div>
        </div>
      </div>
    </div>
    <!--_______________________________________________________________________________________-->
    <div class="col-sm">
      <font size="15">
        <a class="dropdown-item" href="#"><big>Акция</big></a>
        <a class="dropdown-item" href="#"><big>Чаще всего берут</big></a>
        <a class="dropdown-item" href="#"><big>Распродажа</big></a>
        </font>
    </div>
  </div>
</div>
<!--_______________________________________________________________________________________-->

templates/main_page.html
<a size ='10' title="Telegram" href="https://telegram.me/beaver_knithen" target="_blank"><img src="images/telegram_icon.jpg” alt="Написать в Telegram" /></a>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

<header>
<b>
<font size="6">
  <header>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-xxl">
          <a class="navbar-brand" href="#">Beaver_knithen</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" href="#">Доставка и оплата</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#"> О нас </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Контакты</a>
              </li>
                  <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Каталог
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Выбрать модель</a></li>
                  <li><a class="dropdown-item" href="#">Заказать из наличия</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Помощь специалиста</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
              </li> 
              <h5>
              <a  href="https://pngicon.ru/zelenaja-korzina.html"><img src="https://pngicon.ru/file/uploads/basket-128x128.png" 
                alt="корзина" width="40" height="40"> </a>
              </h5>
              <h6>
                <font size="6">
                <li class="nav-item">
                  <a class="nav-link"  href="#">ЛК</a>
                </font size>
                </li>
              </h6>
            </ul>
            
          </div>
        </div>
      </nav>
</header>
</font size>
</b>

<!--_______________________________________________________________________________________-->
<style>
h1 {
  padding-left: 1px;
}
 

</style>

<!--_______________________________________________________________________________________-->
<h1><i>{{beaver_main_1}}</i></h1>
<h2><i>{{beaver_main_2}}</i></h2>        
<!--_______________________________________________________________________________________-->


<!--_______________________________________________________________________________________-->

<!--_______________________________________________________________________________________-->


<div class="container">
  <div class="row">
    <div class="col-sm">
      <h1>
      <div class="col-3">
        <img class = "w-100" src = https://i.pinimg.com/736x/7c/af/0a/7caf0a2961d2a76d98879bf695a644d3.jpg alt = "fon">
      </div>
    </h1>
    </div>
    <!--_______________________________________________________________________________________-->
    <div class="col-sm">
    </div>
    <div class="col">
        <button type="button" class="btn btn-outline-success">Цвет</button>
        <button type="button" class="btn btn-outline-success">Шерсть</button>
        <button type="button" class="btn btn-outline-success">Пошив</button>
        <button type="button" class="btn btn-outline-success">Узоры</button>
        <button type="button" class="btn btn-outline-success">Пол</button>
        <button type="button" class="btn btn-outline-success">Размер</button>
        <button type="button" class="btn btn-outline-success">Страна</button>
        <button type="button" class="btn btn-outline-success">Забрать из наличия</button>

    
        <div class="row">
          <div class="col-5"><form class="d-flex" role="search", col-8>
            <input style="height:70px" class="form-control me-" type="search"  placeholder ="Найти модель" aria-label="Поиск">
            <button class="btn btn-outline-success" type="submit">Поиск</button>
          </form></div>
        </div>
      </div>
    </div>
    <!--_______________________________________________________________________________________-->
    <div class="col-sm">
      <font size="15">
        <a class="dropdown-item" href="#"><big>Акция</big></a>
        <a class="dropdown-item" href="#"><big>Чаще всего берут</big></a>
        <a class="dropdown-item" href="#"><big>Распродажа</big></a>
        </font>
    </div>
  </div>
</div>
<!--_______________________________________________________________________________________-->

templates/products.html
<div class="container">
  <div class="row">
    <div class="col">
      {% if request.args.get('discount') %}
        <a href="{{ url_for('products.main_page') }}" class="btn btn-primary">Показать все товары</a>
        <h2 class="mt-3">Товары со Скидкой</h2>
      {% else %}
        <a href="{{ url_for('products.main_page') }}?discount=true" class="btn btn-primary">Показать только товары со скидкой</a>
        <h2 class="mt-3">Все товары</h2>
      {% endif %}
    </div>
  </div>


  <div class="row">
    {% for product in products %}
      <div class="col-lg-3 col-md-4 col-sm-6 mt-3">
        <div class="card">
          {% if product.thumbnail %}
            <img src="{{ url_for('static', filename=product.thumbnail) }}" class="card-img-top"
                 alt="{{ product.name }}">
          {% endif %}
          <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description|truncate(100) }}</p>
            {% if product.discount %}
              <p class="card-text">Старая цена: <span style="text-decoration: line-through">{{ product.price }}</span>
              </p>
              <p class="card-text">Цена со скидкой: {{ product.price - (product.price / 100 * 30) }}</p>
            {% else %}
              <p class="card-text">Цена: {{ product.price }}</p>
            {% endif %}
            <a href="#" class="btn btn-primary">Подробнее</a>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
</div>